---
- import_playbook: playbooks/10_cfn_network.yml
- import_playbook: playbooks/20_cfn_compute.yml
- import_playbook: playbooks/30_web_config.yml
- import_playbook: playbooks/40_integration_tests.yml