version: 0.2

env:
  variables:
    TEMPLATE_URL: "https://reznichenko.s3.eu-central-1.amazonaws.com/network-stack.template"
    AWS_REGION: "eu-central-1"
    TAG_ENVIRONMENT: "ans-cfn"
  parameter-store:
    VPC_CIDR: "/ansible_test/vpc_cidr"
    PUBLIC_SUBNET_1_CIDR: "/ansible_test/public_subnet_1_cidr"
    PUBLIC_SUBNET_2_CIDR: "/ansible_test/public_subnet_2_cidr"
    PRIVATE_SUBNET_1_CIDR: "/ansible_test/private_subnet_1_cidr"
    PRIVATE_SUBNET_2_CIDR: "/ansible_test/private_subnet_2_cidr"

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install -r requirements.txt -q
  build:
    commands:
      - ansible-playbook -i inventories/aws_ec2.yml playbooks/10_cfn_network.yml --tags create -vvv
  post_build:
    commands:
      - ansible-playbook -i inventories/aws_ec2.yml roles/cfn_network/tests/test.yml
