version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install -r requirements.txt -q
  build:
    commands:
      - ansible-playbook -i inventories/aws_ec2.yml playbooks/40_integration_tests.yml
  post_build:
    commands:
      - ansible-playbook -i inventories/aws_ec2.yml roles/integration_tests/tests/test.yml